add path echo

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -28,7 +28,12 @@ jobs:
           python-version: '3.x'
 
       - name: Install dependencies
-        run: pip install -r ${{ github.action_path }}/requirements.txt
+        run: |
+          echo "Current working directory: $(pwd)"
+          if [ -f requirements.txt ]; then
+            pip install -r requirements.txt
+          else
+            echo "requirements.txt not found" && exit 1
 
       - name: Run Reviewer Script
         env:
